version: "3"
services:
  php:
    container_name: php_${PROJECT_NAME}
    image: ufotech/php:8.4-fpm
    working_dir: ${WORKDIR}
    #    extra_hosts:
    #      - "host.docker.internal:host-gateway"
    environment:
      WORKDIR: ${WORKDIR}
      XDEBUG_CONFIG: remote_host={{YOUR_IP_ADDRESS}}
      PHP_IDE_CONFIG: serverName=docker
      HISTFILE: ${WORKDIR}/var/.bash_history
    volumes:
      - ./:${WORKDIR}
